language: generic
sudo: true
dist: trusty

# whitelist of branches to build
branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq make xsltproc

before_script:
  - wget -O saxon.zip https://downloads.sourceforge.net/project/saxon/Saxon-HE/9.8/SaxonHE9-8-0-4J.zip?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fsaxon%2Ffiles%2FSaxon-HE%2F9.8%2F&ts=1504871167&use_mirror=cytranet 
  - unzip saxon.zip 

#script:
#  - make
#  - git clone https://github.com/commoncriteria/commoncriteria.github.io.git
#  - mkdir -p commoncriteria.github.io/pp/$(basename $TRAVIS_REPO_SLUG)
#  - cp -r output/* commoncriteria.github.io/pp/$(basename $TRAVIS_REPO_SLUG)
#  - cd commoncriteria.github.io
#  - git add --all && git commit -m "Deploying changes"
#  - git pull --rebase
#  - cd -
  
# Deploy HTML pages and updated index.html (needed before we can generate pdf versions)
#deploy:
#  provider: pages
#  skip_cleanup: true
#  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
#  local_dir: commoncriteria.github.io/
#  repo: commoncriteria/commoncriteria.github.io
#  target_branch: master
#  on:
#    branch: master
